### ISSUE TITLE
Failing at Episode 220 - 291

### ISSUE THREAD

**Issue by ThePagel** [gravitypriest/dragon-radar#10]
The "missing" files are in the temp folder
----------------------------
Dragon Radar v1.1.0 "Freeza"
----------------------------
Demuxing DBZ 220 R2...
Demuxing video and audio...
Video & audio demux complete.
Demuxing DBZ 220 R1...
Could not rename .\temp\tmprp13ot\220\R1\AudioFile_80.ac3: [WinError 2] The system cannot find the file specified: '.\\temp\\tmprp13ot\\220\\R1\\2_0.ac3'
Could not rename .\temp\tmprp13ot\220\R1\AudioFile_81.ac3: [WinError 2] The system cannot find the file specified: '.\\temp\\tmprp13ot\\220\\R1\\2_1.ac3'
Could not rename .\temp\tmprp13ot\220\R1\AudioFile_80.ac3: [WinError 2] The system cannot find the file specified: '.\\temp\\tmprp13ot\\220\\R1\\3_0.ac3'
Could not rename .\temp\tmprp13ot\220\R1\AudioFile_81.ac3: [WinError 2] The system cannot find the file specified: '.\\temp\\tmprp13ot\\220\\R1\\3_1.ac3'
Traceback (most recent call last):
  File "__main__.py", line 326, in <module>
  File "__main__.py", line 299, in main
  File "F:\Documents\GitHub\dragon-radar\episode.py", line 178, in demux
  File "F:\Documents\GitHub\dragon-radar\demux.py", line 352, in demux
  File "F:\Documents\GitHub\dragon-radar\demux.py", line 285, in _fuck_the_orange_bricks
  File "F:\Documents\GitHub\dragon-radar\audio.py", line 59, in combine_files
FileNotFoundError: [Errno 2] No such file or directory: '.\\temp\\tmprp13ot\\220\\R1\\2_0.ac3'

**Comment by Danfun64** [comment]
I'm sorry? You post an issue and then close it with no explanation of how the issue was solved? It doesn't appear to have been fixed in a commit or something.
