### ISSUE TITLE
Error Auto-detecting demux information for R1 DBox episode 216

### ISSUE THREAD

**Issue by JTF195** [gravitypriest/dragon-radar#9]
Traceback (most recent call last):
  File "__main__.py", line 326, in <module>
  File "__main__.py", line 296, in main
  File "F:\Documents\GitHub\dragon-radar\episode.py", line 106, in __init__
  File "F:\Documents\GitHub\dragon-radar\auto_detect.py", line 98, in auto_detect
KeyError: '216'

All other episodes work (1-215 and 217-291)

**Comment by JTF195** [comment]
This makes absolutely no sense, but for some reason, changing https://github.com/gravitypriest/dragon-radar/blob/master/params/demux.json#L10682 from DRAGON_BOX_S6_D1 to DRAGON_BOX_S6_D2 fixed the problem for me.

**Comment by JTF195** [comment]
As it turns out, looking at the .autodetect.json generated by dragon-radar, it appears that Season 6 Discs 1-3 are being auto-detected incorrectly.

D1 skips over vid 4, causing ep213-215 to be detected as vid 5-7,

216 completely fails unless you improperly identify it as being on S6D2 in demux.json, in which case it is detected as D2 vid 1, and then 217-222 detect as vid 2-7, and ep223 also (properly) detects as vid 7

Episode 224 should be vid 11, but 224-229 are detected as vids 1-6 and 230 is detected as vid 11

All of the above were already correctly identified in demux.json, and when manually changed in .autodetect.json, they seem to work properly.

**Comment by gravitypriest** [comment]
Thanks for reporting-- I believe I know the source of this issue and will have a fix in the next version
